alias ptivit="source ~/proxy-tivit.sh" 
alias pleap="source ~/proxy-leap.sh" 
alias pnone="source ~/proxy-none.sh" 
alias ..="cd .." 
alias ...="cd ../.."
alias ll="ls -la"
alias cdwork="cd ~/workspace" 
